[build]
publish = "web"

[functions]
node_bundler = "esbuild"

[functions."scheduled_deleteold"]
schedule = "@daily"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
